version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/checkout"
        versions: [">=6.0.3"]
      - dependency-name: "actions/setup-node"
        versions: [">=6.3.0"]
      - dependency-name: "actions/upload-artifact"
        versions: [">=6.0.0"]
